version: '3.8'
services:
  backend:
    build: ./code/backend
    container_name: lecture-backend
    ports:
      - "8000:8000"
    volumes:
      - ./code/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./code/frontend
    container_name: lecture-frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./code/frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
